spring.application.name=user_service
server.port=8080


# ==== DATABASE (MySQL) =====
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://thomas.proxy.rlwy.net:38400/railway}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rQnEIuzygymhULBULQFrqcoOYVXXuKYN}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

file.upload-dir=src/main/resources/static/images/img/
spring.mvc.static-path-pattern=/images/**
spring.web.resources.static-locations=classpath:/static/
# ==== CHARSET (optional) ====
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

# ==== SERVER ====
spring.main.allow-bean-definition-overriding=true
